services:
  # MySQL Database
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Avinash@27
      MYSQL_DATABASE: ticket
    volumes:
      - mysql_data:/var/lib/mysql

  # Adminer (DB UI)
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
    depends_on:
      - db

volumes:
  mysql_data:
